/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'actionType' : string,
  'entityId' : bigint,
  'timestamp' : bigint,
  'details' : string,
  'entityType' : string,
}
export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'authorName' : string,
  'isPinned' : boolean,
}
export interface DevTask {
  'id' : bigint,
  'status' : string,
  'assignee' : [] | [string],
  'title' : string,
  'createdAt' : bigint,
  'dueDate' : [] | [string],
  'description' : string,
  'priority' : string,
}
export interface DiscordMember {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'joinedAt' : bigint,
  'role' : string,
  'discordHandle' : string,
}
export interface Issue {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'severity' : string,
}
export interface Stats {
  'totalTasks' : bigint,
  'totalAnnouncements' : bigint,
  'completedTasks' : bigint,
  'totalMembers' : bigint,
  'openIssues' : bigint,
  'onlineMembers' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[Announcement], bigint>,
  'createDevTask' : ActorMethod<[DevTask], bigint>,
  'createDiscordMember' : ActorMethod<[DiscordMember], bigint>,
  'createIssue' : ActorMethod<[Issue], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteDevTask' : ActorMethod<[bigint], undefined>,
  'deleteDiscordMember' : ActorMethod<[bigint], undefined>,
  'deleteIssue' : ActorMethod<[bigint], undefined>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDevTask' : ActorMethod<[bigint], DevTask>,
  'getDiscordMember' : ActorMethod<[bigint], DiscordMember>,
  'getIssue' : ActorMethod<[bigint], Issue>,
  'getRecentActivity' : ActorMethod<[], Array<Activity>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDevTasksByStatus' : ActorMethod<[string], Array<DevTask>>,
  'listDiscordMembersByRole' : ActorMethod<[string], Array<DiscordMember>>,
  'listIssuesBySeverity' : ActorMethod<[string], Array<Issue>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAnnouncement' : ActorMethod<[Announcement], undefined>,
  'updateDevTask' : ActorMethod<[DevTask], undefined>,
  'updateDiscordMember' : ActorMethod<[DiscordMember], undefined>,
  'updateIssue' : ActorMethod<[Issue], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];