/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'isPinned' : IDL.Bool,
});
export const DevTask = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'assignee' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'priority' : IDL.Text,
});
export const DiscordMember = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : IDL.Text,
  'discordHandle' : IDL.Text,
});
export const Issue = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'severity' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'actionType' : IDL.Text,
  'entityId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'totalAnnouncements' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'totalMembers' : IDL.Nat,
  'openIssues' : IDL.Nat,
  'onlineMembers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
  'createDevTask' : IDL.Func([DevTask], [IDL.Nat], []),
  'createDiscordMember' : IDL.Func([DiscordMember], [IDL.Nat], []),
  'createIssue' : IDL.Func([Issue], [IDL.Nat], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteDevTask' : IDL.Func([IDL.Nat], [], []),
  'deleteDiscordMember' : IDL.Func([IDL.Nat], [], []),
  'deleteIssue' : IDL.Func([IDL.Nat], [], []),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDevTask' : IDL.Func([IDL.Nat], [DevTask], ['query']),
  'getDiscordMember' : IDL.Func([IDL.Nat], [DiscordMember], ['query']),
  'getIssue' : IDL.Func([IDL.Nat], [Issue], ['query']),
  'getRecentActivity' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDevTasksByStatus' : IDL.Func([IDL.Text], [IDL.Vec(DevTask)], ['query']),
  'listDiscordMembersByRole' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DiscordMember)],
      ['query'],
    ),
  'listIssuesBySeverity' : IDL.Func([IDL.Text], [IDL.Vec(Issue)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAnnouncement' : IDL.Func([Announcement], [], []),
  'updateDevTask' : IDL.Func([DevTask], [], []),
  'updateDiscordMember' : IDL.Func([DiscordMember], [], []),
  'updateIssue' : IDL.Func([Issue], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'isPinned' : IDL.Bool,
  });
  const DevTask = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'assignee' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'priority' : IDL.Text,
  });
  const DiscordMember = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : IDL.Text,
    'discordHandle' : IDL.Text,
  });
  const Issue = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'severity' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'actionType' : IDL.Text,
    'entityId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'totalAnnouncements' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'totalMembers' : IDL.Nat,
    'openIssues' : IDL.Nat,
    'onlineMembers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([Announcement], [IDL.Nat], []),
    'createDevTask' : IDL.Func([DevTask], [IDL.Nat], []),
    'createDiscordMember' : IDL.Func([DiscordMember], [IDL.Nat], []),
    'createIssue' : IDL.Func([Issue], [IDL.Nat], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteDevTask' : IDL.Func([IDL.Nat], [], []),
    'deleteDiscordMember' : IDL.Func([IDL.Nat], [], []),
    'deleteIssue' : IDL.Func([IDL.Nat], [], []),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDevTask' : IDL.Func([IDL.Nat], [DevTask], ['query']),
    'getDiscordMember' : IDL.Func([IDL.Nat], [DiscordMember], ['query']),
    'getIssue' : IDL.Func([IDL.Nat], [Issue], ['query']),
    'getRecentActivity' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDevTasksByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DevTask)],
        ['query'],
      ),
    'listDiscordMembersByRole' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DiscordMember)],
        ['query'],
      ),
    'listIssuesBySeverity' : IDL.Func([IDL.Text], [IDL.Vec(Issue)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAnnouncement' : IDL.Func([Announcement], [], []),
    'updateDevTask' : IDL.Func([DevTask], [], []),
    'updateDiscordMember' : IDL.Func([DiscordMember], [], []),
    'updateIssue' : IDL.Func([Issue], [], []),
  });
};

export const init = ({ IDL }) => { return []; };